### ISSUE TITLE
Upgrade GPU

### ISSUE THREAD

**Issue by justincase141** [planeklm/razed-cryptomining#6]
I am having an issue where when we upgrade the GPU, it stays on the 480. Anything specific I should look into to change?

**Comment by planeklm** [comment]
Any server or client sided errors?

**Comment by justincase141** [comment]
Negative, logs show "bought miner" when installed.

**Comment by planeklm** [comment]
Could you explain what happens when you upgrade the gpu? e.g does the item get given, does it do the animation, does it give the email.

**Comment by justincase141** [comment]
No email, it gives the mini game and once completed it installs and says "enjoy the mining" or something along the lines of that notification in the top right corner of the screen.

**Comment by planeklm** [comment]
What phone do you have currently installed on the server?

**Comment by planeklm** [comment]
I believe it may be a problem with the database, as stated in this function.
![image](https://github.com/planeklm/razed-cryptomining/assets/91488137/79b6b585-6ba3-496c-8e65-ebe38d28a510)

**Comment by planeklm** [comment]
Make sure to have the latest oxmysql and have installed the .sql into your database.

**Comment by justincase141** [comment]
We have roadphone

**Comment by planeklm** [comment]
Make sure to comment out sendmail and sendgpumail in the server.lua. These are for qb-phone/emails.
