### ISSUE TITLE
On/Off picture

### ISSUE THREAD

**Issue by Lucasmillen1** [planeklm/razed-cryptomining#7]
I used to be able to see it, but even on fresh installs, I cannot seem to see the picture that pops up when the crypto is online. Do you have a link to that photo?
![cryptopic](https://github.com/planeklm/razed-cryptomining/assets/145896347/e08428b5-b591-4a4f-95a2-804585516359)

**Comment by Lucasmillen1** [comment]
Replaced the links, all good now! 
![stoppedcrypto](https://github.com/planeklm/razed-cryptomining/assets/145896347/a3f1b3b6-66e5-46f0-9a2e-3a8b4cc92dea)

**Comment by planeklm** [comment]
Yeah, seems to be an issue with imgur, will most likely replace them in the future.
