### ISSUE TITLE
ox_target issue

### ISSUE THREAD

**Issue by Pipo1978** [planeklm/razed-cryptomining#8]
I'm facing an issue trying to use ox_target, below the error message:

[     45687] [FiveM_b3095_GT]             MainThrd/ ^1SCRIPT ERROR: @ox_target/client/api.lua:70: expected options to have type 'array' (received hash table)^7
[     45687] [FiveM_b3095_GT]             MainThrd/ ^3> typeError^7 (^5@ox_target/client/api.lua^7:70)
[     45687] [FiveM_b3095_GT]             MainThrd/ ^3> addTarget^7 (^5@ox_target/client/api.lua^7:112)
[     45687] [FiveM_b3095_GT]             MainThrd/ ^3> ref^7 (^5@ox_target/client/api.lua^7:223)
[     45687] [FiveM_b3095_GT]             MainThrd/ ^3> fn^7 (^5@razed-cryptomining/client/client.lua^7:312)
[     45687] [FiveM_b3095_GT]             MainThrd/ ^1SCRIPT ERROR: @razed-cryptomining/client/client.lua:312: 
[     45687] [FiveM_b3095_GT]             MainThrd/ ^5 An error occurred while calling export `addModel` in resource `ox_target`:
[     45687] [FiveM_b3095_GT]             MainThrd/ 
[     45687] [FiveM_b3095_GT]             MainThrd/ ^5 ---^7

Can someone help on this? Thanks! ;)

**Comment by planeklm** [comment]
Make sure to update your ox_target to the latest release.
